- name: Clone Crane repository
  git:
    dest: '{{ pulp_devel_dir }}/pulpproject.org'
    repo: https://github.com/pulp/pulpproject.org.git
  become_user: '{{ pulp_user }}'

- name: Install packages
  package: name={{ item }} state=present
  with_items:
      - gcc
      - ruby-devel
      - zlib-devel
      - rubygem-bundler

- name: Install pulpproject.org gems
  bundler:
      gemfile: "{{ pulp_devel_dir }}/pulpproject.org/Gemfile"
  become_user: '{{ pulp_user }}'
