- include: '{{ pulp_install_strategy }}.yml'

- name: Create /var/lib/pulp directory
  file:
    path: /var/lib/pulp
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Create /var/lib/pulp/tmp directory
  file:
    path: /var/lib/pulp/tmp
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Create /etc/pulp
  file:
    path: /etc/pulp
    state: directory

- name: Find server.yaml
  find:
    paths: '{{ pulp_devel_dir if pulp_install_strategy == "development" else pulp_venv }}'
    recurse: true
    patterns: 'server.yaml'
  register: result

- name: Assert one server.yaml file has been found
  assert:
    that: 'result["files"] | length == 1'

- name: Install /etc/pulp/server.yaml
  copy:
    src: '{{ result["files"][0]["path"] }}'
    remote_src: true
    dest: /etc/pulp/server.yaml
    # This file is about to be customized, and it's also especially likely to be
    # customized by a user. The down-side of doing this is that this
    # configuration file can become out of sync with sources.
    force: false

- name: Generate random secret for server.yaml
  shell: tr -dc 'a-z0-9!@#$%^&*(\-_=+)' < /dev/urandom | head -c 50
  changed_when: false
  check_mode: false
  register: result

# TODO: Conditionally execute this task.
- name: Add SECRET_KEY to server.yaml
  lineinfile:
    path: /etc/pulp/server.yaml
    regexp: '^SECRET_KEY: '
    line: "SECRET_KEY: '{{ result.stdout }}'"

- name: Enable DEBUG mode in server.yaml
  lineinfile:
    path: /etc/pulp/server.yaml
    regexp: '^DEBUG: '
    line: 'DEBUG: True'
    state: '{{ "present" if pulp_install_strategy == "development" else "absent" }}'
