- name: Clone Pulp Smash repository
  git:
    dest: '{{ pulp_devel_dir }}/crane'
    repo: https://github.com/PulpQE/pulp-smash.git
  become_user: '{{ pulp_user }}'

- block:
  - name: Create pulp-smash config dir
    file:
        path: "{{ pulp_user_home }}/.config/pulp_smash"
        state: directory

  - name: Install pulp-smash config
    template:
        src: templates/smash-settings.j2
        dest: "{{ pulp_user_home }}/.config/pulp_smash/settings.json"

  - name: Install pulp-smash requirements
    pip:
      virtualenv: "{{ pulp_smash_venv | default(omit) }}"
      virtualenv_command: /usr/bin/python3 -m venv
      state: latest
      requirements: "{{ pulp_devel_dir }}/pulp-smash/{{ item }}"
      chdir: "{{ pulp_devel_dir }}/pulp-smash"
    with_items:
      - requirements.txt
      - requirements-dev.txt

  - name: Enable autoenv directory Switching for pulp-smash
    lineinfile:
      dest: "{{ pulp_smash_venv }}/.project"
      line: "{{ pulp_devel_dir }}/pulp-smash"
      create: true
      regexp: ".*"
    when: pulp_smash_venv is defined

  - name: Enable psmash alias
    copy:
      src: files/smash.bashrc
      dest: "{{ pulp_user_home }}/.bashrc.d/smash.bashrc"
    when: pulp_install_strategy == 'development'

  become_user: '{{ pulp_user }}'
