---
# Install Pulp 3 from source.
#
# The resultant installation is designed to be useful for end users. It doesn't
# do things like install code in editable mode, install extra dependencies or
# install Bash aliases.
- hosts: all
  become: true
  vars:
    pulp_install_strategy: source
  roles:
    - pulp-user
    - db
    - broker
    - lazy
    - dev
    - plugins
    - reset_db
    - systemd
