---
# Install Pulp 3 from PyPI.
#
# The resultant installation is designed to be useful for end users. It doesn't
# do things like install code in editable mode, install extra dependencies or
# install Bash aliases.
- hosts: all
  become: true
  pre_tasks:
    # Pulp 3 isn't currently compatible with SELinux.
    - name: Disable selinux
      selinux:
        state: disabled
  roles:
    - pulp-user
    - db
    - broker
    - lazy
    - dev
    - plugins
    - reset_db
    - systemd
