- name: Clone Crane repository
  git:
    dest: '{{ pulp_devel_dir }}/crane'
    repo: https://github.com/pulp/crane.git
    version: '3.0-dev'
  become_user: '{{ pulp_user }}'

- name: Install crane config
  template:
      src: templates/crane-conf.j2
      dest: "{{ pulp_devel_dir }}/crane/crane.conf"
  become_user: '{{ pulp_user }}'

- name: Install setup_crane_links script
  template:
      src: templates/setup-crane-links.j2
      dest: /usr/bin/setup_crane_links
      mode: 0755

- name: Add Crane to bashrc.d
  copy:
    src: files/crane.bashrc
    dest: "{{ pulp_user_home }}/bashrc.d/crane.bashrc"
  when: pulp_include_bashrc

- name: Setup crane links
  command: setup_crane_links
  args:
      creates: /var/lib/pulp/published/docker/v1
  # This command fails when "setfacl" is called on sshfs-provided files, even when run as root
  ignore_errors: True
